.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MADBOMBER 6 "January 21, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
madbomber \- a clone of Activision's classic Atari 2600 game, "Kaboom! 
.SH SYNOPSIS
.B madbomber [--disable-sound] [--fullscreen] [--help] [--usage]
.\"[DISPLAY]
.SH DESCRIPTION
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
Instead, it has documentation in /usr/share/doc/madbomber/README.txt.gz

\fB"Mad Bomber"\fP is is a clone of Activision's classic Atari 2600 console
game, "Kaboom!," by Larry Kaplan, with spruced-up graphics and
sound effects, and music.


.SH OPTIONS
.TP
.B \--disable-sound
If sound support was compiled in, this will
disable it for this session of the game.
.TP
.B \--fullscreen
Run in fullscreen mode. 
(Note: Under Linux, if this doesn't work,
you will need to run the game as root.)
.TP
.B \--help
Display a help message summarizing command-line options, copyright, 
and game controls.
.TP
.B \--usage
Display a brief message summarizing command-line options.
.TP

.SH AUTHOR
This manual page was written by Christian T. Steigies <cts@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
